In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

In [3]:
data = pd.read_csv('Churn_Modelling.csv')
x = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


# Label Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
x[:, 2] = encoder.fit_transform( x[:,2] )

print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One Hot Encoding the 'Geography' column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

column_encoder = ColumnTransformer( transformers=[ ( 'encoder', OneHotEncoder(), [1] ) ], remainder='passthrough' )
x = np.array( column_encoder.fit_transform(x) )

print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Train Test Split

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state = 0 )

print( x.shape, x_train.shape, x_test.shape )

(10000, 12) (8000, 12) (2000, 12)


# Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform( x_train )
x_test = sc.fit_transform( x_test )

print(x_train)
print(x_test)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]
[[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504
   1.62356528]]


# Building the ANN

In [11]:
ann = tf.keras.models.Sequential()

## Adding input layer and the first hidden layer

In [12]:
ann.add( tf.keras.layers.Dense( units=6, activation='relu' ) )

## Adding the second hidden layer

In [13]:
ann.add( tf.keras.layers.Dense( units=6, activation='relu' ) )

## Adding the output layer

In [14]:
ann.add( tf.keras.layers.Dense( units=1, activation='sigmoid' ) )

# Training the ANN

## Compiling the ANN

In [15]:
ann.compile( optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'] )

In [16]:
ann.fit( x_train, y_train, batch_size = 32, epochs = 100 )

Epoch 1/100
250/250 [==============================] - 0s 788us/step - loss: 0.5622 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 783us/step - loss: 0.5039 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 825us/step - loss: 0.4765 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 776us/step - loss: 0.4557 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 773us/step - loss: 0.4397 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 787us/step - loss: 0.4313 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 809us/step - loss: 0.4274 - accuracy: 0.7987
Epoch 8/100
250/250 [==============================] - 0s 796us/step - loss: 0.4252 - accuracy: 0.8139
Epoch 9/100
250/250 [==============================] - 0s 920us/step - loss: 0.4234 - accuracy: 0.8177
Epoch 10/100
250/250 [==============================] - 0s 786us/step - l

# Making the predictions and evaluating the model

In [18]:
print(ann.predict( sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]) ) > 0.5)

[[False]]


# Predicting the Test set results

In [20]:
x_train_predictions = ann.predict( x_test )

x_train_predictions = ( x_train_predictions > 0.5 )

print( np.concatenate( (x_train_predictions.reshape(len(x_train_predictions), 1), (y_test.reshape(len(y_test), 1))), 1 ) )

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Making a Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix( y_test, x_train_predictions )

print(cm)

accuracy_score( y_test, x_train_predictions )

[[1523   72]
 [ 211  194]]


0.8585