In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

In [3]:
data = pd.read_excel('Folds5x2_pp.xlsx')

data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split( x, y, test_size = 0.2, random_state = 0 )

print( x.shape, x_train.shape, x_test.shape )

(9568, 4) (7654, 4) (1914, 4)


# Building the ANN

In [6]:
ann = tf.keras.models.Sequential()

In [7]:
ann.add( tf.keras.layers.Dense( units = 6, activation = 'relu' ) )

In [8]:
ann.add( tf.keras.layers.Dense( units = 6, activation = 'relu' ) )

In [9]:
ann.add( tf.keras.layers.Dense( units = 1 ) )

# Training the ANN

In [10]:
ann.compile( optimizer = 'adam', loss = 'mean_squared_error' )

In [11]:
ann.fit( x_train, y_train, batch_size = 32, epochs = 100 )

Epoch 1/100
240/240 [==============================] - 0s 801us/step - loss: 14325.6104
Epoch 2/100
240/240 [==============================] - 0s 749us/step - loss: 336.5507
Epoch 3/100
240/240 [==============================] - 0s 723us/step - loss: 325.1688
Epoch 4/100
240/240 [==============================] - 0s 802us/step - loss: 311.0975
Epoch 5/100
240/240 [==============================] - 0s 768us/step - loss: 294.5510
Epoch 6/100
240/240 [==============================] - 0s 767us/step - loss: 276.2861
Epoch 7/100
240/240 [==============================] - 0s 776us/step - loss: 256.4612
Epoch 8/100
240/240 [==============================] - 0s 836us/step - loss: 236.0370
Epoch 9/100
240/240 [==============================] - 0s 770us/step - loss: 215.4028
Epoch 10/100
240/240 [==============================] - 0s 780us/step - loss: 194.4859
Epoch 11/100
240/240 [==============================] - 0s 893us/step - loss: 174.3690
Epoch 12/100
240/240 [============================

240/240 [==============================] - 0s 729us/step - loss: 26.9366
Epoch 97/100
240/240 [==============================] - 0s 723us/step - loss: 26.9896
Epoch 98/100
240/240 [==============================] - 0s 725us/step - loss: 26.5233
Epoch 99/100
240/240 [==============================] - 0s 754us/step - loss: 26.6628
Epoch 100/100
240/240 [==============================] - 0s 735us/step - loss: 26.4752


# Predicting the results of the Test set

In [13]:
y_pred = ann.predict( x_test )

np.set_printoptions( precision=2 )

print(  np.concatenate( (y_pred.reshape(len(y_pred), 1), (y_test.reshape(len(y_test), 1))), 1 ) )

[[430.04 431.23]
 [461.03 460.01]
 [464.51 461.14]
 ...
 [471.75 473.26]
 [438.6  438.  ]
 [457.78 463.28]]
